-- 코드를 입력하세요
SELECT FLAVOR
FROM(SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDERS
    FROM (
        SELECT FLAVOR, TOTAL_ORDER FROM JULY
        UNION ALL
        SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
    ) AS COMBINED_TABLE
    GROUP BY FLAVOR
    ORDER BY TOTAL_ORDERS DESC
) AS FLAVOR
LIMIT 3;